services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
    - .env
    # environment:
    #   - NODE_ENV=development
    #   - PORT=5000
    #   - MONGODB_URI=mongodb+srv://billahmukim:111222@news-dev.iwahvy9.mongodb.net/?retryWrites=true&w=majority&appName=news-dev
    #   - JWT_SECRET=your_jwt_secret
    #   - AWS_REGION=ap-south-1
    #   - AWS_ACCESS_KEY_ID=your_aws_access_key
    #   - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
    #   - S3_BUCKET_NAME=abulovoski
    #   - FRONTEND_URL=http://localhost:5173

# services:
#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongodb
#     environment:
#       - NODE_ENV=development
#       - PORT=5000
#       - MONGODB_URI=mongodb://mongodb:27017/video-upload
#       - JWT_SECRET=your_jwt_secret
#       - AWS_REGION=ap-south-1
#       - AWS_ACCESS_KEY_ID=your_aws_access_key
#       - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
#       - S3_BUCKET_NAME=abulovoski
#       - FRONTEND_URL=http://localhost:5173

#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data: